name: PlayerJoinChecker
version: @version@
main: xyz.n7mn.dev.playerjoinchecker.PlayerJoinChecker
authors: [ 7mi_chan ]
description: PlayerJoinChecker

commands:
  perm:
    usage: '/perm <mcid>'
    description: ''
  join:
    usage: '/join <rank>'
    description: ''
  joinall:
    usage: '/joinall'
    description: ''